# Generated by Django 5.2 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_clean_onboarding_accesses"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="gweder_properties",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Gweder document properties (ref, date, audience, metadata)",
                null=True,
            ),
        ),
    ]
